<!-- app/code/Dolphin/TutorialPlugin/view/adminhtml/templates/settings.phtml -->
<?php $actionUrl = $block->getUrl('tutorialplugin/settings/index'); ?>
<form action="<?php echo $actionUrl; ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>" />

    <h1><?php echo __('Tutorial Plugin Settings'); ?></h1>
    <p><?php echo __('Here you can configure your plugin.'); ?></p>
</form>

<!-- You can add forms, tables, and other HTML content here -->
